alias sudo='doas'
# alias up='yay --diffmenu --answerdiff All --save -Syu'
alias up='yay -Syu'
alias i='sudo pacman -Syu'
alias s='yay -Ss'
alias clean='paccache -rk 1 && yay -Yc'
alias pacnews='arch_news_check'
alias zshnew='source ~/.zshrc'
alias locai='ollama serve && ollama'
alias pw='pass.py'
alias sn='shutdown now'
alias sp='systemctl suspend'
alias rb='reboot'

alias fan="watch -n 1 'sensors | grep fan'"

alias gs='la && git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'


alias nano='micro'
alias vim='nvim'
alias nv='nvim'
alias mic='micro'

alias see='bat'
alias clipwipe='rm ~/.cache/cliphist/db'
alias view='gwenview'
alias zat='zathura'
alias find='fd'


alias docs='cd Documents'
alias rice='cd Rice'
alias uni='cd uniStuff'
alias dl='cd Downloads'
alias sz='du -sh * | sort -h'
alias y='yazi'
unalias ls
alias ls='eza --sort=modified --reverse --color=always --icons --git --group-directories-first'
alias lc='ls -l'
alias la='lc -A'
alias lsa='lc -G'
alias lt='ls -T'
alias rm='rm -I'
alias tp='trashy put'
alias tl='trashy list'
alias te='trashy empty'
alias tr='trashy restore'
alias x='exit'
alias c='clear'
alias cd='z'

alias color='color_check'
alias grep='rg --color=auto --line-number --smart-case'

alias clock='tty-clock -s -c -C 4'
alias ff='fastfetch'
alias ffs='ff -c ~/.config/fastfetch/min.jsonc'
alias dw='dysk'

alias aq='asciiquarium'
alias plis='sudo'
