# export GTK_THEME=adw-gtk3-dark
export LS_COLORS=""
export COLORTERM=truecolor
export BAT_THEME="base16"
export "MICRO_TRUECOLOR=1"
export EZA_CONFIG_DIR="$HOME/.config/eza/"
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=kitty
export MANPAGER="nvim +Man!"

export PATH="$HOME/.cargo/bin:$PATH"
export GOPATH=$HOME/.go
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.local/opt/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH=$PATH:/home/reval/.spicetify
export PATH=~/.npm-global/bin:$PATH
export PATH="/home/reval/.local/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
