 [main]
font=Carbonsevka:size=12
pad=8x4
underline-offset=10px
underline-thickness=1px

[colors-dark]
# alpha=0.85
foreground=f2f4f8
background=161616

regular0=262626   
regular1=fa4d56   
regular2=cff27e  
regular3=e28413   
regular4=78a9ff   
regular5=be95ff   
regular6=3ddbd9   
regular7=e6edf3

bright0=525252  
bright1=fa4d56   
bright2=cff27e  
bright3=e28413   
bright4=78a9ff   
bright5=be95ff   
bright6=3ddbd9   
bright7=dde1e6

selection-foreground=f2f4f8
selection-background=393939

urls=78a9ff

cursor=161616 dde1e6
search-box-no-match=161616 ffafd2
search-box-match=f2f4f8 525252

jump-labels=161616 e28413

# overrides
200=ff7eb6
201=ee5396 
202=8d8d8d


[bell]
urgent=no
notify=no
command-focused=no

