[main]
font=Iosevka Nerd Font:size=12
pad=8x4
underline-offset=8px
underline-thickness=1px

[colors-dark]
foreground=f2f4f8
background=161616

regular0=262626   
regular1=fa4d56   
regular2=cff27e  
regular3=E28413   
regular4=78a9ff   
regular5=be95ff   
regular6=3ddbd9   
regular7=e6edf3

bright0=525252  
bright1=ff8389
bright2=e3ff9e
bright3=ffb066
bright4=a6c8ff
bright5=d4bbff
bright6=6ff0ee
bright7=dde1e6

selection-foreground=f2f4f8
selection-background=393939

urls=78a9ff

# overrides
200=ee5396 
201=ff7eb6


[bell]
urgent=no
notify=no
command-focused=no

